SOURCES := \
	tests.c \
	test_bug.c \
	test_fslookup.c \
	test_galloc.c \
	test_irqs.c \
	test_kqueue.c \
	test_mm.c \
	test_panic.c \
	test_pckbd.c \
	test_pf.c \
	test_rootfs.c \
	test_serial.c \
	test_slice_alloc.c \
	test_threads.c

include $(PRJROOT)/tools/main.mk

